"""Add certificate management to vhosts

Revision ID: 0bc86f680ecc
Revises: d4e9f3a1b2c5
Create Date: 2026-06-10 22:10:10.777273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bc86f680ecc'
down_revision: Union[str, Sequence[str], None] = 'd4e9f3a1b2c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vhosts', sa.Column('ssl_provider', sa.String(length=20), server_default='none', nullable=False))
    op.add_column('vhosts', sa.Column('ssl_cert', sa.Text(), nullable=True))
    op.add_column('vhosts', sa.Column('ssl_key', sa.Text(), nullable=True))
    op.add_column('vhosts', sa.Column('ssl_expires_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vhosts', 'ssl_expires_at')
    op.drop_column('vhosts', 'ssl_key')
    op.drop_column('vhosts', 'ssl_cert')
    op.drop_column('vhosts', 'ssl_provider')
    # ### end Alembic commands ###
